"""Create user and task tables

Revision ID: d6338e4ed4e9
Revises: dc511ccd61aa
Create Date: 2024-08-19 21:28:11.446880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6338e4ed4e9'
down_revision: Union[str, None] = 'dc511ccd61aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
